version: '3.9'

services:
  api:
    build: .
    networks:
      - default
    ports:
      - '3000:3000'
    command: ["dumb-init", "node", "./node_modules/.bin/agendash", "--db=${AGENDA_MONGO_DB}", "--collection=${AGENDA_COLLECTION}", "--port=${PORT}"]

networks:
  default:
    external: true
    name: tuf
